version: 2.1
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate ami.json
          command: packer validate ami.json

  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: |
            packer build \
              -var "aws_region=${aws_region}" \
              -var "aws_access_key=${aws_access_key}" \
              -var "aws_secret_key=${aws_secret_key}" \
              -var "subnet_id=${subnet_id}" \
              -var "ami_users=${ami_users}" \
              ami.json
          no_output_timeout: 30m

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - validate
      - build-base:
           filters:
              branches:
                only: master
           requires:
            - validate