version: 2.1
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate ami.json
          command: packer validate ami.json

  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Install Packer
          command: |
            cd ~/
            cd packer
            wget https://releases.hashicorp.com/packer/0.9.0/packer_0.9.0_linux_386.zip
            unzip packer_0.9.0_linux_386.zip
            echo "export PATH=$PATH:~/packer/" >> ~/.bashrc
      - run:
          command: pwd && ls
      - run:
          name: Build base
          command: |
            ./packer build \
              -var "aws_region=us-east-1" \
              -var "aws_access_key=${aws_access_key}" \
              -var "aws_secret_key=${aws_secret_key}" \
              -var "subnet_id=subnet-09c00b56" \
              ami.json
          no_output_timeout: 30m

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          filters:
            branches:
              only: master